site_name: Hydra-genetics
nav:
  - Introduction: index.md
  - Modules: modules.md
  - How-to make a pipeline:
    - Create a pipeline skeleton: make_pipeline/create.md
    - Import modules and rules: make_pipeline/import.md
    - Pipeline configuration: make_pipeline/config.md
    - Result files: make_pipeline/results.md
  - How-to run a pipeline:
    - Cluster profile: run_pipeline/profile.md
    - Create sample files: run_pipeline/create_sample_files.md
    - Make a python environment: run_pipeline/environment.md
  - How-to run on a restricted cluster:
    - Pipeline adjustments: packaging_pipeline/prepare_pipeline.md
    - Build pipeline package: packaging_pipeline/package_pipeline.md
    - Installing pipeline on restricted cluster: packaging_pipeline/unpack_pipeline.md
  - Development:
    - Snakemake rules: development/rules.md
    - Code standards: development/standards.md
    - Code testing: development/testing.md
    - Help code: development/help_code.md
  - Tutorials:
    - Make a simple pipeline: tutorials/simple_pipeline.md


theme: readthedocs
extra_css: [extra.css]
theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs/", "workflow/rules/"]
      url_download: "True"
  - mdx_spanner
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
